#!/usr/bin/ash

run_hook() {
    modprobe -a -q dm-crypt >/dev/null 2>&1
    modprobe loop
    [ "${quiet}" = "y" ] && CSQUIET=">/dev/null"
    local USB_LUKS_HEADER_DISK='/dev/disk/by-id/XXXXX'
    local USB_LUKS_HEADER_OFFSET=0K
    local USB_LUKS_HEADER_SIZE=0M
    local USB_LUKS_HEADER=/dev/luks_header
    local USB_LUKS_KEYFILE=/etc/keyfile
    local USB_LUKS_CRYPTDEVICE=/dev/disk/by-id/XXXXX
    local USB_LUKS_DECRYPTEDDM=crypt

    while [ ! -L $USB_LUKS_HEADER_DISK ]; do
     echo 'Waiting for header...'
     sleep 1
    done

    ln -s $(losetup -o $USB_LUKS_HEADER_OFFSET --sizelimit $USB_LUKS_HEADER_SIZE -f --show $USB_LUKS_HEADER_DISK) $USB_LUKS_HEADER
    cryptsetup --allow-discards --header $USB_LUKS_HEADER -d $USB_LUKS_KEYFILE open $USB_LUKS_CRYPTDEVICE $USB_LUKS_DECRYPTEDDM
}

build() {
    local mod

    add_module "loop"
    add_module "dm-crypt"
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules "/crypto/"
    fi

    add_binary "losetup"
    add_binary "cryptsetup"
    add_binary "dmsetup"
    add_file "/etc/keyfile"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary "/usr/lib/libgcc_s.so.1"

    add_runscript
}

help() {
    cat <<HELPEOF
The content below is not for this hook.

This hook allows for an encrypted root device. Users should specify the device
to be unlocked using 'cryptdevice=device:dmname' on the kernel command line,
where 'device' is the path to the raw device, and 'dmname' is the name given to
the device after unlocking, and will be available as /dev/mapper/dmname.

For unlocking via keyfile, 'cryptkey=device:fstype:path' should be specified on
the kernel cmdline, where 'device' represents the raw block device where the key
exists, 'fstype' is the filesystem type of 'device' (or auto), and 'path' is
the absolute path of the keyfile within the device.

Without specifying a keyfile, you will be prompted for the password at runtime.
This means you must have a keyboard available to input it, and you may need
the keymap hook as well to ensure that the keyboard is using the layout you
expect.
HELPEOF
}
